use crate::Packet;
use crate::parse_packet;
use std::slice;

pub struct PacketHandle<'a>(pub Packet<'a>);

/// Parses a packet from a raw C pointer.
///
/// # Safety
/// `data` must be a valid pointer to a contiguous block of memory of at least `len` bytes.
/// The caller must ensure the memory outlives the returned `PacketHandle`.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn packet_parse(data: *const u8, len: usize) -> *mut PacketHandle<'static> {
    if data.is_null() || len == 0 {
        return std::ptr::null_mut();
    }

    let slice = unsafe { slice::from_raw_parts(data, len) };

    match parse_packet(slice) {
        Ok(packet) => {
            let handle = Box::new(PacketHandle(packet));

            unsafe {
                let handle_static: Box<PacketHandle<'static>> = std::mem::transmute(handle);
                Box::into_raw(handle_static)
            }
        }
        Err(_) => std::ptr::null_mut(),
    }
}

/// Frees the allocated PacketHandle.
///
/// # Safety
/// `handle` must be a valid pointer generated by `packet_parse`.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn packet_free(handle: *mut PacketHandle<'static>) {
    if !handle.is_null() {
        let _ = unsafe { Box::from_raw(handle) };
    }
}
